version: '3.8'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app/

  postgres:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=employee_db
    volumes:
#      - ./postgres:/var/lib/postgresql/data
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
    restart: always

